// <auto-generated />
using System;
using CryptoBot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptoBot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("CryptoBot.Domain.Aggregates.OrderAggregate.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AverageFillPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientOrderId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Commission")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExchangeOrderId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FilledQuantity")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LimitPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionSide")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Side")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("StopPrice")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StrategyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientOrderId");

                    b.HasIndex("ExchangeOrderId");

                    b.HasIndex("Status");

                    b.HasIndex("StrategyId");

                    b.HasIndex("Symbol", "Status");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("CryptoBot.Domain.Aggregates.PositionAggregate.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CurrentPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Leverage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarginMode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RealizedPnL")
                        .HasColumnType("TEXT");

                    b.Property<int>("Side")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("StopLossPrice")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StrategyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TakeProfitPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCommission")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TrailingStopPercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TrailingStopPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsClosed");

                    b.HasIndex("StrategyId");

                    b.HasIndex("Symbol", "IsClosed");

                    b.ToTable("Positions", (string)null);
                });

            modelBuilder.Entity("CryptoBot.Domain.Aggregates.StrategyAggregate.Strategy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CumulativePnL")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("LosingTrades")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxDrawdown")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PeakPnL")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StoppedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WinningTrades")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Strategies", (string)null);
                });

            modelBuilder.Entity("CryptoBot.Infrastructure.Backtesting.Persistence.HistoricalKlineRecord", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Interval")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Close")
                        .HasPrecision(28, 12)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("High")
                        .HasPrecision(28, 12)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Low")
                        .HasPrecision(28, 12)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Open")
                        .HasPrecision(28, 12)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Volume")
                        .HasPrecision(28, 12)
                        .HasColumnType("TEXT");

                    b.HasKey("Symbol", "Interval", "OpenTime");

                    b.ToTable("HistoricalKlines", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
